### ISSUE TITLE
Calling via NixOS configuration.nix (no flakes)

### ISSUE THREAD

**Issue by koalaeagle** [hardenedlinux/zeek2nix#14]
Is there a way to deploy this via a standard configuration.nix file (no flakes) on NixOS?

I am trying to deploy zeek on NixOS, I found an official package but I don't see an associated service. I believe you have done some work in this space, so appreciate any insights!

**Comment by GTrunSec** [comment]
You can import the nixosmodule by importFrormTarll.

- example https://github.com/GTrunSec/photoprism2nix#native-nix-support
- https://github.com/hardenedlinux/zeek2nix/blob/main/cells/zeek/overlays/nixos/standalone.nix#L7
replace the `cell.nixosModules.zeek`  to `zeek2nix.nixosModules.zeek`, which is your import name.

**Comment by GTrunSec** [comment]
simple config without flake: https://github.com/hardenedlinux/zeek2nix/blob/main/nix/zeek/overlays/nixos/standalone.nix#L7

**Comment by koalaeagle** [comment]
Thanks for your help & effort here!
